### ISSUE TITLE
Contribute and participate in hacktoberfest by completing the following program

### ISSUE THREAD

**Issue by its-Kumar** [its-Kumar/Python_Projects#1]
Contribute to this file and make a alarm clock project in python and participate in #hacktoberfest2021

https://github.com/its-Kumar/Python_Projects/blob/471bea6f51b8c001ef3e33c593bb2b510a531441/Final%20Capstone%20Project/Alarm_clock.py
Final Capstone Project/Alarm_clock.py

**Comment by JanviRaina** [comment]
Hey, I would like to contribute in this project.

**Comment by JanviRaina** [comment]
Do we have to write a python program or build a gui using it?

**Comment by its-Kumar** [comment]
> Do we have to write a python program or build a gui using it?

This is your choice you can build GUI or simple console based program

**Comment by JanviRaina** [comment]
Okay will do this.
You can assign this to me.

**Comment by its-Kumar** [comment]
> Okay will do this. You can assign this to me.

Done
