### ISSUE TITLE
contribute to any of the python projects - Hacktoberfest

### ISSUE THREAD

**Issue by its-Kumar** [its-Kumar/Python_Projects#2]
Participating in hacktoberfest 2021
Contribute to any of my python projects I will accept all valid PRs

Thank you,
Happy Hacking

**Comment by SnehaKapoo1** [comment]
Yes, I want to contribute.
Can you assign me any of your projects?

**Comment by AyushSolanki-17** [comment]
Hey..!! I want to contribute in your repo. Can you assign me a project or can I add a new project in your repository..

**Comment by its-Kumar** [comment]
@SnehaKapoo1 @AyushSolanki-17 You can choose any project from the repo, or you can add a new one also

**Comment by its-Kumar** [comment]
> Please add me as a contributor. I am well acquainted with html , css, js , c++ , c , python

You can send pull request any time
